CREATE TABLE IF NOT EXISTS domain_verifications (
    id SERIAL PRIMARY KEY,
    filename TEXT UNIQUE NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
